const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.NinePatch,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Plugins.Avix_PokiSDK_ForC3,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Share,
		C3.Plugins.BinaryData,
		C3.Plugins.Text,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.ScriptsInEvents.Ev_poki_Event4_Act1,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestCommercialBreak,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.CommercialBreakPossible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnRewardedBreakComplete,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.LastAdRewardSuccess,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnCommercialBreakComplete,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Avix_PokiSDK_ForC3.Exps.CommercialBreakPossible,
		C3.Plugins.Avix_PokiSDK_ForC3.Exps.AdBlockDetected,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStop,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.IsPreview,
		C3.ScriptsInEvents.Evloading_Event7_Act1,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Exps.layerindex,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Exps.max,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.NinePatch.Acts.SetX,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Text.Exps.LayerNumber,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceHeight,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceWidth,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Pin.Exps.PinnedUID,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Exps.layerscrolly,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Exps.ZIndex,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.TiledBg.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.TiledBg.Exps.Opacity,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnError,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnCleared,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{partName: 0},
	{isFurniture: 0},
	{tilesW: 0},
	{tilesH: 0},
	{rotation: 0},
	{layers: 0},
	{pinUID: 0},
	{layerOverride: 0},
	{selfHSL: 0},
	{HSLindex: 0},
	{isRef: 0},
	{iconScale: 0},
	{iconOffX: 0},
	{iconOffY: 0},
	{gridData: 0},
	{Zpos: 0},
	{Xmax: 0},
	{Ymax: 0},
	{Xmin: 0},
	{Ymin: 0},
	{thumbnailAsset: 0},
	{isSticker: 0},
	{portX: 0},
	{portY: 0},
	{isBottomMenu: 0},
	{partBed: 0},
	{partBed2: 0},
	{partWindow: 0},
	{partBed3: 0},
	{partWindow2: 0},
	{partWindow3: 0},
	{partTable: 0},
	{partTable2: 0},
	{partSeat: 0},
	{partSeat2: 0},
	{partDresser: 0},
	{partDresser2: 0},
	{partCarpet: 0},
	{partCarpet2: 0},
	{partCarpet3: 0},
	{partCarpet4: 0},
	{partCarpet5: 0},
	{partCarpet6: 0},
	{partCarpet7: 0},
	{partCarpet8: 0},
	{partCarpet9: 0},
	{partDesk: 0},
	{partPlant: 0},
	{partPlant2: 0},
	{partPlant3: 0},
	{partWindow4: 0},
	{partWindow5: 0},
	{partWindow6: 0},
	{partWindow7: 0},
	{partBookshelf: 0},
	{partPet: 0},
	{partPet2: 0},
	{partPet3: 0},
	{partPet4: 0},
	{partPet5: 0},
	{partPet6: 0},
	{partFan: 0},
	{partTV: 0},
	{partDresser3: 0},
	{partBookshelf2: 0},
	{partKeyboard: 0},
	{partPet7: 0},
	{partBookshelf3: 0},
	{partCarpet10: 0},
	{partSeat3: 0},
	{partSeat4: 0},
	{partSeat5: 0},
	{partSeat6: 0},
	{partSeat7: 0},
	{partWeights: 0},
	{partLamp: 0},
	{partPlant4: 0},
	{partPlant5: 0},
	{partTable3: 0},
	{partPet8: 0},
	{partPet9: 0},
	{partPet10: 0},
	{partCarpet11: 0},
	{partWindow8: 0},
	{partWindow9: 0},
	{partWindow10: 0},
	{partWindow11: 0},
	{partWindow12: 0},
	{partWindow13: 0},
	{partWindow14: 0},
	{partWindow15: 0},
	{partWindow16: 0},
	{partWindow17: 0},
	{partWindow18: 0},
	{partWindow19: 0},
	{partSeat8: 0},
	{partSeat9: 0},
	{partSeat10: 0},
	{partTable4: 0},
	{partTable5: 0},
	{partTable6: 0},
	{partTable7: 0},
	{partWindow20: 0},
	{partWindow21: 0},
	{partTree: 0},
	{partHeater: 0},
	{partChimney1: 0},
	{partChimney2: 0},
	{partPresents: 0},
	{sublayer: 0},
	{selfLuminosity: 0},
	{skipPart: 0},
	{buttonScale: 0},
	{buttonYoffset: 0},
	{buttonSkipTint: 0},
	{hasBlank: 0},
	{overrideParts: 0},
	{hslValue: 0},
	{layerNames: 0},
	{partWalls: 0},
	{partFloor: 0},
	{partBackground: 0},
	{partLayer: 0},
	{partNum: 0},
	{isLocked: 0},
	{spawnIndex: 0},
	{targetLayout: 0},
	{luminosity: 0},
	{baseScale: 0},
	{altTween: 0},
	{btnPart: 0},
	{btnTab: 0},
	{extraLayers: 0},
	{sublayers: 0},
	{refIndex: 0},
	{btnColor: 0},
	{Tween: 0},
	{uiPartIcon: 0},
	{Pin: 0},
	{uiLock: 0},
	{btnPlay: 0},
	{btnStyle: 0},
	{btnBack: 0},
	{btnColorToggle: 0},
	{btnRandom: 0},
	{btnSnapshot: 0},
	{sprInputArea: 0},
	{isAppearing: 0},
	{bkgFade: 0},
	{Rotate: 0},
	{Sine: 0},
	{sprLoadSpin: 0},
	{"9pColorEdge": 0},
	{curColor: 0},
	{curPart: 0},
	{curStyle: 0},
	{curTab: 0},
	{sprLogo: 0},
	{type: 0},
	{posMove: 0},
	{lock: 0},
	{btnScroll: 0},
	{maxTop: 0},
	{maxBottom: 0},
	{DragDrop: 0},
	{sprScrollBar: 0},
	{sprBlank: 0},
	{bkgFadeB: 0},
	{Timer: 0},
	{btnFailSafe: 0},
	{HSLvalues: 0},
	{btnHSL: 0},
	{bkgOverlayCover: 0},
	{sprOverlayCover: 0},
	{uiColorScrollArea: 0},
	{uiItemScrollArea: 0},
	{curPremium: 0},
	{prtBats: 0},
	{btnNewPart: 0},
	{dragUID: 0},
	{isDragging: 0},
	{sprDraggable: 0},
	{btnTrash: 0},
	{btnRotate: 0},
	{btnOK: 0},
	{btnMute: 0},
	{frameHSL: 0},
	{btnReset: 0},
	{btnReset_OK: 0},
	{btnReset_Cancel: 0},
	{PokiSDK: 0},
	{Keyboard: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{Audio: 0},
	{Mouse: 0},
	{Share: 0},
	{BinaryData: 0},
	{txtChilet: 0},
	{txtLabel: 0},
	{txtLabel2: 0},
	{txtRef: 0},
	{txtTopLayer: 0},
	{txtBreeSerif_version: 0},
	{txtBreeSerif2: 0},
	{txtChiletLogo: 0},
	{txtNew: 0},
	{Sprite: 0},
	{isFloor: 0},
	{coorX: 0},
	{coorY: 0},
	{isFoundation: 0},
	{sprTile: 0},
	{offsetX: 0},
	{offsetY: 0},
	{tileUID: 0},
	{sprSnapshade: 0},
	{sprRef: 0},
	{txtGrid: 0},
	{sprGrid: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{txtWallGrid: 0},
	{isShown: 0},
	{framePartMenu: 0},
	{sprSelectedPart: 0},
	{frameParts: 0},
	{sprScrollFrame: 0},
	{frameParts2: 0},
	{sprBorders: 0},
	{valMin: 0},
	{valMax: 0},
	{val: 0},
	{sprScrolling: 0},
	{sprSelectedColor: 0},
	{txtFirstData: 0},
	{thumbFloor: 0},
	{thumbWalls: 0},
	{thumbBackground: 0},
	{popUp: 0},
	{bgPopUp: 0},
	{txtNewData: 0},
	{txtBasicLabel: 0},
	{txtNewLocks: 0},
	{famPinRefParts: 0},
	{famRoomParts: 0},
	{famResposive: 0},
	{famWallStuff: 0},
	{famThumbs: 0},
	{famParts: 0},
	{famBtnParts: 0},
	{famButtons: 0},
	{famCursors: 0},
	{TransitionAngle: 0},
	{PK_GAMEPLAY_STOPPED: 0},
	{details: 0},
	{category: 0},
	{tag: 0},
	{placement: 0},
	{gapX: 0},
	{gapY: 0},
	{startY: 0},
	{startX: 0},
	{perLine: 0},
	{reScale: 0},
	{currentColorIndex: 0},
	{layer: 0},
	{gameMode: 0},
	{modeLevel: 0},
	{BASIC_AD_LOCKED_PERCENT: 0},
	{COLOR_AD_LOCKED_PERCENT: 0},
	{INPUT_LAST_X: 0},
	{INPUT_LAST_Y: 0},
	{CLAMP_TAB_X: 0},
	{CLAMP_TAB_Y: 0},
	{CLAMP_BUTTONS_Y: 0},
	{CLAMP_COLORS_Y: 0},
	{TOGGLE_COLORS_ON: 0},
	{DEFAULT_SCROLL_X: 0},
	{DEFAULT_SCROLL_Y: 0},
	{CLAMP_COLORS_X: 0},
	{NO_INPUT: 0},
	{START_CATEGORY: 0},
	{CURRENT_CATEGORY: 0},
	{CURRENT_HSL: 0},
	{CATEGORIES_FIXED: 0},
	{INPUT_FIRST_TIME: 0},
	{widthScale: 0},
	{layerCount: 0},
	{baseWidth: 0},
	{spawnRatio: 0},
	{baseSide: 0},
	{lowerBorder: 0},
	{partType: 0},
	{currentPartIndex: 0},
	{totalLayers: 0},
	{layerName: 0},
	{currentNewItems: 0},
	{posOffset: 0},
	{selfLayer: 0},
	{totalLayerAssets: 0},
	{sourceUID: 0},
	{btnPartMaxY: 0},
	{btnNewPartMaxY: 0},
	{premiumOnSide: 0},
	{finalY: 0},
	{oddLineOffset: 0},
	{currentColorRGB: 0},
	{currentColorHSL: 0},
	{currentSubLayer: 0},
	{currentSubLayersString: 0},
	{currentExtraLayers: 0},
	{currentLayerString: 0},
	{colorPick: 0},
	{maxHorV: 0},
	{UID: 0},
	{horConstraint: 0},
	{vertConstraint: 0},
	{lastCategory: 0},
	{popSize: 0},
	{popSize2: 0},
	{btnHSL_UID: 0},
	{hideColor: 0},
	{snapshotSize: 0},
	{part: 0},
	{frame: 0},
	{w: 0},
	{h: 0},
	{portCLAMP: 0},
	{wheelStep: 0},
	{move: 0},
	{aux_spawnIndex: 0},
	{spawnLayer: 0},
	{newObjUID: 0},
	{baseTileW: 0},
	{baseTileH: 0},
	{edgeTop: 0},
	{edgeBottom: 0},
	{edgeLeft: 0},
	{edgeRight: 0},
	{AUX_VAR: 0},
	{AUX_STRING: 0},
	{isLandscape: 0},
	{floorXo: 0},
	{floorYo: 0},
	{dragOffset: 0},
	{INPUT_HOLD_COUNTER: 0},
	{IS_OBJECT_HELD: 0},
	{INPUT_LAST_OBJECT: 0},
	{INPUT_ROTATE_THRESHOLD: 0},
	{INPUT_DRAG_THRESHOLD: 0},
	{GRID_CURRENT: 0},
	{GRID_ROOM: 0},
	{GRID_EMPTY: 0},
	{WALL_GRID_CURRENT: 0},
	{WALL_GRID_EMPTY: 0},
	{WALL_GRID_ROOM: 0},
	{MOVE_AROUND: 0},
	{DEBUG_VIDEO_ON: 0},
	{DEBUG_HUD_ON: 0},
	{DEBUG_SHADE_ON: 0},
	{tol: 0},
	{foundIt: 0},
	{currentUID: 0},
	{partUID: 0},
	{objUID: 0},
	{x0: 0},
	{y0: 0},
	{longestSide: 0},
	{extraOffsetX: 0},
	{extraOffsetY: 0},
	{tileDiff: 0},
	{signProd: 0},
	{drawShade: 0},
	{stepY: 0},
	{stepX: 0},
	{gridReset: 0},
	{heldTimer: 0},
	{turnOn: 0},
	{refX: 0},
	{tileBase: 0},
	{tileW: 0},
	{tileH: 0},
	{tileSideCount: 0},
	{tileXo: 0},
	{tileYo: 0},
	{angOffset: 0},
	{tileWidth: 0},
	{tileHeight: 0},
	{tileRatio: 0},
	{xo: 0},
	{yo: 0},
	{ang: 0},
	{flip: 0},
	{leftSide: 0},
	{tileSide: 0},
	{pickedLine: 0},
	{currentGrid: 0},
	{x: 0},
	{y: 0},
	{newValue: 0},
	{pickedSide: 0},
	{otherSide: 0},
	{lineIndex: 0},
	{side: 0},
	{overlappedGrid: 0},
	{gridA: 0},
	{gridB: 0},
	{isOverlapping: 0},
	{vertOffset: 0},
	{tw: 0},
	{th: 0},
	{signX: 0},
	{signY: 0},
	{minSide: 0},
	{extraOffX: 0},
	{extraOffY: 0},
	{gridValue: 0},
	{isSet: 0},
	{closestUID: 0},
	{closestDist: 0},
	{flipThreshold: 0},
	{tileCoorX: 0},
	{color: 0},
	{opacity: 0},
	{overlapUID: 0},
	{canMove: 0},
	{coorXoff: 0},
	{coorYoff: 0},
	{tileColor: 0},
	{onTop: 0},
	{shadeData: 0},
	{maxX: 0},
	{maxY: 0},
	{minX: 0},
	{minY: 0},
	{depthTolerance: 0},
	{oldOffX: 0},
	{oldOffY: 0},
	{aux: 0},
	{rot: 0},
	{fixAxis: 0},
	{scaleChange: 0},
	{sizeChange: 0},
	{originAndLength: 0},
	{objArray: 0},
	{firstLeftVal: 0},
	{firstRightVal: 0},
	{secondLeftVal: 0},
	{secondRightVal: 0},
	{z: 0},
	{currentLine: 0},
	{ObjUID: 0},
	{axis: 0},
	{diagon: 0},
	{outY: 0},
	{inY: 0},
	{cursorOffset: 0},
	{isNew: 0},
	{auxX: 0},
	{auxY: 0},
	{facing: 0},
	{colorHSL: 0},
	{catTypeA: 0},
	{catTypeB: 0},
	{currentCategory: 0},
	{newCategory: 0},
	{value: 0},
	{RELEASE_PLATFORM: 0},
	{ORIENTATION: 0},
	{IS_MUTED: 0},
	{ADS_HAS_AD_BLOCKER: 0},
	{ADBLOCKER_CHECKED: 0},
	{ADS_LAST_TAG: 0},
	{ADS_GAME_PLAYING: 0},
	{availability: 0},
	{adFailsafeTimeout: 0},
	{adFailSafeButtonEndSize: 0},
	{adFailSafe_CurrentHold: 0},
	{SAVED_DATA_STRING: 0},
	{SAVED_AUX: 0},
	{OLD_SAVED_NEW_ITEMS: 0},
	{SAVED_DEFAULT_DATA: 0},
	{SAVED_OLD_DEFAULT_DATA: 0},
	{saveString: 0},
	{firstHalfString: 0},
	{secondHalfString: 0},
	{index: 0},
	{replaceData: 0},
	{isColor: 0},
	{availableBoolean: 0},
	{resultingSaveString: 0},
	{layersDiff: 0},
	{currentPart: 0},
	{oldData: 0},
	{newData: 0},
	{newDataAttachment: 0},
	{dataDiffCount: 0},
	{blankExtra: 0},
	{replacedText: 0},
	{legacySaveString: 0},
	{newDefaultSaveString: 0},
	{RESET_TEXT: 0},
	{COLOR_OK: 0},
	{COLOR_CANCEL: 0},
	{COLOR_FADED: 0},
	{SAVE_data: 0},
	{SAVE_version: 0},
	{SAVE_FIRST_DATA: 0},
	{SAVE_LATEST_VERSION: 0},
	{SAVE_loadOK: 0},
	{SAVED_NEW_ITEMS: 0},
	{resultingData: 0},
	{currLayerData: 0},
	{prevLayersData: 0},
	{postLayersData: 0},
	{pickedLayerIndex: 0},
	{replaceValue: 0},
	{isInList: 0},
	{currLockedList: 0},
	{currItem: 0},
	{lastVersion: 0},
	{newVersion: 0},
	{pos: 0}
];

self.InstanceType = {
	partBed: class extends self.ISpriteInstance {},
	partBed2: class extends self.ISpriteInstance {},
	partWindow: class extends self.ISpriteInstance {},
	partBed3: class extends self.ISpriteInstance {},
	partWindow2: class extends self.ISpriteInstance {},
	partWindow3: class extends self.ISpriteInstance {},
	partTable: class extends self.ISpriteInstance {},
	partTable2: class extends self.ISpriteInstance {},
	partSeat: class extends self.ISpriteInstance {},
	partSeat2: class extends self.ISpriteInstance {},
	partDresser: class extends self.ISpriteInstance {},
	partDresser2: class extends self.ISpriteInstance {},
	partCarpet: class extends self.ISpriteInstance {},
	partCarpet2: class extends self.ISpriteInstance {},
	partCarpet3: class extends self.ISpriteInstance {},
	partCarpet4: class extends self.ISpriteInstance {},
	partCarpet5: class extends self.ISpriteInstance {},
	partCarpet6: class extends self.ISpriteInstance {},
	partCarpet7: class extends self.ISpriteInstance {},
	partCarpet8: class extends self.ISpriteInstance {},
	partCarpet9: class extends self.ISpriteInstance {},
	partDesk: class extends self.ISpriteInstance {},
	partPlant: class extends self.ISpriteInstance {},
	partPlant2: class extends self.ISpriteInstance {},
	partPlant3: class extends self.ISpriteInstance {},
	partWindow4: class extends self.ISpriteInstance {},
	partWindow5: class extends self.ISpriteInstance {},
	partWindow6: class extends self.ISpriteInstance {},
	partWindow7: class extends self.ISpriteInstance {},
	partBookshelf: class extends self.ISpriteInstance {},
	partPet: class extends self.ISpriteInstance {},
	partPet2: class extends self.ISpriteInstance {},
	partPet3: class extends self.ISpriteInstance {},
	partPet4: class extends self.ISpriteInstance {},
	partPet5: class extends self.ISpriteInstance {},
	partPet6: class extends self.ISpriteInstance {},
	partFan: class extends self.ISpriteInstance {},
	partTV: class extends self.ISpriteInstance {},
	partDresser3: class extends self.ISpriteInstance {},
	partBookshelf2: class extends self.ISpriteInstance {},
	partKeyboard: class extends self.ISpriteInstance {},
	partPet7: class extends self.ISpriteInstance {},
	partBookshelf3: class extends self.ISpriteInstance {},
	partCarpet10: class extends self.ISpriteInstance {},
	partSeat3: class extends self.ISpriteInstance {},
	partSeat4: class extends self.ISpriteInstance {},
	partSeat5: class extends self.ISpriteInstance {},
	partSeat6: class extends self.ISpriteInstance {},
	partSeat7: class extends self.ISpriteInstance {},
	partWeights: class extends self.ISpriteInstance {},
	partLamp: class extends self.ISpriteInstance {},
	partPlant4: class extends self.ISpriteInstance {},
	partPlant5: class extends self.ISpriteInstance {},
	partTable3: class extends self.ISpriteInstance {},
	partPet8: class extends self.ISpriteInstance {},
	partPet9: class extends self.ISpriteInstance {},
	partPet10: class extends self.ISpriteInstance {},
	partCarpet11: class extends self.ISpriteInstance {},
	partWindow8: class extends self.ISpriteInstance {},
	partWindow9: class extends self.ISpriteInstance {},
	partWindow10: class extends self.ISpriteInstance {},
	partWindow11: class extends self.ISpriteInstance {},
	partWindow12: class extends self.ISpriteInstance {},
	partWindow13: class extends self.ISpriteInstance {},
	partWindow14: class extends self.ISpriteInstance {},
	partWindow15: class extends self.ISpriteInstance {},
	partWindow16: class extends self.ISpriteInstance {},
	partWindow17: class extends self.ISpriteInstance {},
	partWindow18: class extends self.ISpriteInstance {},
	partWindow19: class extends self.ISpriteInstance {},
	partSeat8: class extends self.ISpriteInstance {},
	partSeat9: class extends self.ISpriteInstance {},
	partSeat10: class extends self.ISpriteInstance {},
	partTable4: class extends self.ISpriteInstance {},
	partTable5: class extends self.ISpriteInstance {},
	partTable6: class extends self.ISpriteInstance {},
	partTable7: class extends self.ISpriteInstance {},
	partWindow20: class extends self.ISpriteInstance {},
	partWindow21: class extends self.ISpriteInstance {},
	partTree: class extends self.ISpriteInstance {},
	partHeater: class extends self.ISpriteInstance {},
	partChimney1: class extends self.ISpriteInstance {},
	partChimney2: class extends self.ISpriteInstance {},
	partPresents: class extends self.ISpriteInstance {},
	partWalls: class extends self.ISpriteInstance {},
	partFloor: class extends self.ISpriteInstance {},
	partBackground: class extends self.ISpriteInstance {},
	btnPart: class extends self.ISpriteInstance {},
	btnTab: class extends self.ISpriteInstance {},
	btnColor: class extends self.ISpriteInstance {},
	uiPartIcon: class extends self.ISpriteInstance {},
	uiLock: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnStyle: class extends self.ISpriteInstance {},
	btnBack: class extends self.ISpriteInstance {},
	btnColorToggle: class extends self.ISpriteInstance {},
	btnRandom: class extends self.ISpriteInstance {},
	btnSnapshot: class extends self.ISpriteInstance {},
	sprInputArea: class extends self.ISpriteInstance {},
	bkgFade: class extends self.ITiledBackgroundInstance {},
	sprLoadSpin: class extends self.ISpriteInstance {},
	_9pColorEdge: class extends self.IWorldInstance {},
	curColor: class extends self.ISpriteInstance {},
	curPart: class extends self.ISpriteInstance {},
	curStyle: class extends self.ISpriteInstance {},
	curTab: class extends self.ISpriteInstance {},
	sprLogo: class extends self.ISpriteInstance {},
	btnScroll: class extends self.ISpriteInstance {},
	sprScrollBar: class extends self.ISpriteInstance {},
	sprBlank: class extends self.ISpriteInstance {},
	bkgFadeB: class extends self.ITiledBackgroundInstance {},
	btnFailSafe: class extends self.ISpriteInstance {},
	btnHSL: class extends self.ISpriteInstance {},
	bkgOverlayCover: class extends self.ITiledBackgroundInstance {},
	sprOverlayCover: class extends self.ISpriteInstance {},
	uiColorScrollArea: class extends self.ISpriteInstance {},
	uiItemScrollArea: class extends self.ISpriteInstance {},
	curPremium: class extends self.ISpriteInstance {},
	prtBats: class extends self.IParticlesInstance {},
	btnNewPart: class extends self.ISpriteInstance {},
	sprDraggable: class extends self.ISpriteInstance {},
	btnTrash: class extends self.ISpriteInstance {},
	btnRotate: class extends self.ISpriteInstance {},
	btnOK: class extends self.ISpriteInstance {},
	btnMute: class extends self.ISpriteInstance {},
	frameHSL: class extends self.ISpriteInstance {},
	btnReset: class extends self.ISpriteInstance {},
	btnReset_OK: class extends self.ISpriteInstance {},
	btnReset_Cancel: class extends self.ISpriteInstance {},
	PokiSDK: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Share: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	txtChilet: class extends self.ITextInstance {},
	txtLabel: class extends self.ITextInstance {},
	txtLabel2: class extends self.ITextInstance {},
	txtRef: class extends self.ITextInstance {},
	txtTopLayer: class extends self.ITextInstance {},
	txtBreeSerif_version: class extends self.ITextInstance {},
	txtBreeSerif2: class extends self.ITextInstance {},
	txtChiletLogo: class extends self.ITextInstance {},
	txtNew: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	sprTile: class extends self.ISpriteInstance {},
	sprSnapshade: class extends self.ISpriteInstance {},
	sprRef: class extends self.ISpriteInstance {},
	txtGrid: class extends self.ITextInstance {},
	sprGrid: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	txtWallGrid: class extends self.ITextInstance {},
	framePartMenu: class extends self.IWorldInstance {},
	sprSelectedPart: class extends self.ISpriteInstance {},
	frameParts: class extends self.IWorldInstance {},
	sprScrollFrame: class extends self.IWorldInstance {},
	frameParts2: class extends self.IWorldInstance {},
	sprBorders: class extends self.ISpriteInstance {},
	sprScrolling: class extends self.IWorldInstance {},
	sprSelectedColor: class extends self.ISpriteInstance {},
	txtFirstData: class extends self.ITextInstance {},
	thumbFloor: class extends self.ISpriteInstance {},
	thumbWalls: class extends self.ISpriteInstance {},
	thumbBackground: class extends self.ISpriteInstance {},
	popUp: class extends self.IWorldInstance {},
	bgPopUp: class extends self.ITiledBackgroundInstance {},
	txtNewData: class extends self.ITextInstance {},
	txtBasicLabel: class extends self.ITextInstance {},
	txtNewLocks: class extends self.ITextInstance {},
	famPinRefParts: class extends self.ISpriteInstance {},
	famRoomParts: class extends self.ISpriteInstance {},
	famResposive: class extends self.ISpriteInstance {},
	famWallStuff: class extends self.ISpriteInstance {},
	famThumbs: class extends self.ISpriteInstance {},
	famParts: class extends self.ISpriteInstance {},
	famBtnParts: class extends self.ISpriteInstance {},
	famButtons: class extends self.ISpriteInstance {},
	famCursors: class extends self.ISpriteInstance {}
}